### ISSUE TITLE
Поменять стратегию проверки доступности

### ISSUE THREAD

**Issue by b3cat** [b3cat/spotify_in_russia#11]
Сейчас мы полагаемся на какую-то эвристику о том, что при выходе споти появится русский язык на странице выбора языка, что в общем-то никем не гарантируется. 

Нужно поменять стратегию: делать проверку наличия редиректа по урлу `https://www.spotify.com/ru-ru`, наличие редиректа означает недоступность, при этом вариант работает независимо от физического положения сервера, на котором проводится тест.

**Comment by leominov** [comment]
Лучше `https://www.spotify.com/ru-ru/`
